# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ViewModel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ViewModel(object):
    def setupUi(self, ViewModel):
        ViewModel.setObjectName("ViewModel")
        ViewModel.resize(846, 653)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ViewModel.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(ViewModel)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(ViewModel)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.comboBoxVar = QtWidgets.QComboBox(self.frame)
        self.comboBoxVar.setMinimumSize(QtCore.QSize(70, 27))
        self.comboBoxVar.setMaximumSize(QtCore.QSize(70, 16777215))
        self.comboBoxVar.setObjectName("comboBoxVar")
        self.horizontalLayout.addWidget(self.comboBoxVar)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBoxTimeStep = QtWidgets.QComboBox(self.frame)
        self.comboBoxTimeStep.setMinimumSize(QtCore.QSize(70, 27))
        self.comboBoxTimeStep.setMaximumSize(QtCore.QSize(70, 16777215))
        self.comboBoxTimeStep.setObjectName("comboBoxTimeStep")
        self.horizontalLayout.addWidget(self.comboBoxTimeStep)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBoxAxis = QtWidgets.QComboBox(self.frame)
        self.comboBoxAxis.setMinimumSize(QtCore.QSize(50, 27))
        self.comboBoxAxis.setMaximumSize(QtCore.QSize(50, 16777215))
        self.comboBoxAxis.setObjectName("comboBoxAxis")
        self.horizontalLayout.addWidget(self.comboBoxAxis)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEditOffset = QtWidgets.QLineEdit(self.frame)
        self.lineEditOffset.setMinimumSize(QtCore.QSize(40, 27))
        self.lineEditOffset.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEditOffset.setObjectName("lineEditOffset")
        self.horizontalLayout.addWidget(self.lineEditOffset)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEditXRotation = QtWidgets.QLineEdit(self.frame)
        self.lineEditXRotation.setMinimumSize(QtCore.QSize(40, 27))
        self.lineEditXRotation.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEditXRotation.setObjectName("lineEditXRotation")
        self.horizontalLayout.addWidget(self.lineEditXRotation)
        self.lineEditYRotation = QtWidgets.QLineEdit(self.frame)
        self.lineEditYRotation.setMinimumSize(QtCore.QSize(40, 27))
        self.lineEditYRotation.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEditYRotation.setObjectName("lineEditYRotation")
        self.horizontalLayout.addWidget(self.lineEditYRotation)
        self.lineEditZRotation = QtWidgets.QLineEdit(self.frame)
        self.lineEditZRotation.setMinimumSize(QtCore.QSize(40, 27))
        self.lineEditZRotation.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEditZRotation.setText("")
        self.lineEditZRotation.setObjectName("lineEditZRotation")
        self.horizontalLayout.addWidget(self.lineEditZRotation)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonMakePNG = QtWidgets.QPushButton(self.frame)
        self.pushButtonMakePNG.setObjectName("pushButtonMakePNG")
        self.horizontalLayout.addWidget(self.pushButtonMakePNG)
        self.verticalLayout.addWidget(self.frame)
        self.graphicsView = QtWidgets.QGraphicsView(ViewModel)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)

        self.retranslateUi(ViewModel)
        QtCore.QMetaObject.connectSlotsByName(ViewModel)

    def retranslateUi(self, ViewModel):
        _translate = QtCore.QCoreApplication.translate
        ViewModel.setWindowTitle(_translate("ViewModel", "Просмотр результатов моделирования"))
        self.label_5.setText(_translate("ViewModel", "Переменная:"))
        self.label.setText(_translate("ViewModel", "Время:"))
        self.label_2.setText(_translate("ViewModel", "Разрез:"))
        self.label_3.setText(_translate("ViewModel", "Смещение:"))
        self.label_4.setText(_translate("ViewModel", "Поворот:"))
        self.pushButtonMakePNG.setText(_translate("ViewModel", "Показать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ViewModel = QtWidgets.QDialog()
    ui = Ui_ViewModel()
    ui.setupUi(ViewModel)
    ViewModel.show()
    sys.exit(app.exec_())
